; SPDX-License-Identifier: GPL-3.0-or-later
; One pinned style for every platform. Qt Quick Controls otherwise picks a
; per-platform default, which is the opposite of the one-UI goal.
[Controls]
Style=Material

[Material]
Theme=Dark
Accent=Teal
Primary=BlueGrey
