#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate the full-chain I/Q decode fixtures in tests/fixtures/iq.

The fixtures are short cu8 baseband captures plus dsd-neo-iq metadata sidecars.
Replaying them with --iq-replay drives the complete chain (decimation, filtering,
discriminator/CQPSK timing, symbol slicer, frame sync, protocol layer), which is
what the DECODE_IQ_* CTest cases assert against.

Two source kinds feed the same output format:

  "iq"     the upstream recording already is complex baseband; it is resampled to
           48 kHz and requantized to cu8.
  "audio"  the upstream recording is FM discriminator audio with no I/Q. Because
           FM demodulation is invertible, the audio is treated as instantaneous
           frequency and integrated back into a complex baseband signal. The
           result exercises the same demodulation chain, but carries none of the
           original RF impairments (noise, fading, adjacent-channel energy).

Fixtures are committed, so this script is provenance and regeneration only -- it
is not run by CI and needs network access plus ffmpeg. Regenerated bytes are not
guaranteed bit-identical across ffmpeg versions; re-run the DECODE_IQ_* tests
after regenerating.

Usage:
    python3 tools/build_iq_fixtures.py [--out tests/fixtures/iq] [--cache .iq-cache]
"""

import argparse
import math
import os
import subprocess
import sys
import urllib.request
import zipfile

import numpy as np

SAMPLE_RATE_HZ = 48000
DSP_BW_KHZ = 48  # keeps demod rate at 48 kHz -> integer samples/symbol for every mode
DEFAULT_DEVIATION = 0.35  # remodulation deviation as a fraction of Nyquist

# Upstream sources. The Signal Identification Wiki publishes no explicit
# content license, so no CC claim is made for that material (short off-air
# excerpts redistributed for testing with attribution); the m17-fme sample is
# GPL. THIRD_PARTY.md is the authoritative attribution/licensing notice.
SOURCES = {
    "p25_c4fm_cc_if": "https://www.sigidwiki.com/images/4/4a/P25_C4FM-CC_BEE0014C_IF.wav",
    "p25_c4fm_vc_if": "https://www.sigidwiki.com/images/2/25/P25-C4FM-VC_IF.wav",
    "p25_cqpsk_cc_if": "https://www.sigidwiki.com/images/c/cb/P25_CQPSK-CC_920650D5_IF.wav",
    "p25_cqpsk_vc_if": "https://www.sigidwiki.com/images/a/ab/P25_CQPSK-VC_91FE5105_IF.wav",
    "p25_sacch": "https://www.sigidwiki.com/images/3/39/SACCH.mp3",
    "dmr_mototrbo": "https://www.sigidwiki.com/images/d/d2/DMRMOTOTRBO_Sound.mp3",
    "dmr_t3_cc": "https://www.sigidwiki.com/images/b/b8/DMR_Control_Channel_454580kHz_AF.mp3",
    "nxdn_iq_zip": "https://www.sigidwiki.com/images/0/03/NXDN_IQ.zip",
    "dpmr_zip": "https://www.sigidwiki.com/images/e/e0/DPMR.zip",
    "dstar": "https://www.sigidwiki.com/images/2/2e/DStar_Sound.mp3",
    "ysf": "https://www.sigidwiki.com/images/2/26/Yaesu_sys_fusion.wav",
    "edacs": "https://www.sigidwiki.com/images/a/a8/EDACS96_Sound.mp3",
    "m17": "https://raw.githubusercontent.com/lwvmobile/m17-fme/main/samples/m17_clear_voice_wav.wav",
}

# Members to extract from zipped sources.
ZIP_MEMBERS = {
    "nxdn_iq_zip": {"nxdn48_iq": "NXDN48 IQ.wav", "nxdn96_iq": "NXDN96 IQ.wav"},
    "dpmr_zip": {"dpmr_iq": "SDRSharp_20160101_231640Z_12kHz_IQ.wav"},
}

# name, source key, kind, start_s, duration_s, deviation (audio kind only)
FIXTURES = [
    ("p25p1_c4fm_cc", "p25_c4fm_cc_if", "iq", 0, 2, None),
    ("p25p1_c4fm_vc", "p25_c4fm_vc_if", "iq", 0, 3, None),
    ("p25p1_cqpsk_cc", "p25_cqpsk_cc_if", "iq", 0, 2, None),
    ("p25p1_cqpsk_vc", "p25_cqpsk_vc_if", "iq", 0, 2, None),
    ("p25p2_cc", "p25_sacch", "audio", 0, 2, 0.35),
    ("dmr_voice", "dmr_mototrbo", "audio", 0, 2, 0.35),
    ("dmr_t3_cc", "dmr_t3_cc", "audio", 0, 2, 0.35),
    ("nxdn48", "nxdn48_iq", "iq", 0, 6, None),
    ("nxdn96", "nxdn96_iq", "iq", 0, 2, None),
    ("dpmr", "dpmr_iq", "iq", 0, 10, None),
    ("dstar", "dstar", "audio", 0, 4, 0.35),
    ("ysf", "ysf", "audio", 0, 6, 0.35),
    ("edacs", "edacs", "audio", 0, 2, 0.35),
    # M17 needs a narrower synthetic deviation; see docs/testing.md for the
    # caveat about M17 decoding better from native baseband than through I/Q.
    ("m17", "m17", "audio", 0, 8, 0.15),
]

METADATA_TEMPLATE = """{{
  "format": "dsd-neo-iq",
  "version": 1,
  "sample_format": "cu8",
  "iq_order": "IQ",
  "endianness": "none",
  "capture_stage": "post_mute_pre_widen",
  "sample_rate_hz": {sample_rate},
  "center_frequency_hz": 851375000,
  "capture_center_frequency_hz": 851375000,
  "ppm": 0,
  "tuner_gain_tenth_db": 270,
  "rtl_dsp_bw_khz": {bw_khz},
  "base_decimation": 1,
  "post_downsample": 1,
  "demod_rate_hz": {demod_rate},
  "offset_tuning_enabled": false,
  "fs4_shift_enabled": false,
  "combine_rotate_enabled": false,
  "muted_bytes_excluded": true,
  "contains_retunes": false,
  "capture_retune_count": 0,
  "source_backend": "rtl",
  "source_args": "fixture",
  "capture_started_utc": "1970-01-01T00:00:00Z",
  "data_file": "{data_file}",
  "data_bytes": {data_bytes},
  "capture_drops": 0,
  "capture_drop_blocks": 0,
  "input_ring_drops": 0,
  "notes": "generated by tools/build_iq_fixtures.py"
}}
"""


def fetch(cache_dir, key, url):
    """Download url into cache_dir, returning the local path.

    Only the hard-coded https URLs in SOURCES are ever fetched; the scheme guard
    below rejects anything else so a local file:// or ftp:// path cannot be
    substituted by editing a source list entry.
    """
    if not url.startswith("https://"):
        raise ValueError(f"refusing non-https fixture source for {key}: {url}")
    path = os.path.join(cache_dir, key + os.path.splitext(url)[1])
    if os.path.exists(path) and os.path.getsize(path) > 0:
        return path
    # URLs come only from the SOURCES constant above and are guarded to https.
    req = urllib.request.Request(url, headers={"User-Agent": "dsd-neo-fixture-builder"})  # nosemgrep: python.lang.security.audit.dynamic-urllib-use-detected.dynamic-urllib-use-detected
    with urllib.request.urlopen(req) as resp:  # nosemgrep: python.lang.security.audit.dynamic-urllib-use-detected.dynamic-urllib-use-detected
        data = resp.read()
    with open(path, "wb") as handle:
        handle.write(data)
    return path


def extract_zip_members(cache_dir, key, archive_path):
    """Extract the members named in ZIP_MEMBERS[key], returning {name: path}."""
    out = {}
    with zipfile.ZipFile(archive_path) as zf:
        for name, member in ZIP_MEMBERS[key].items():
            dest = os.path.join(cache_dir, name + ".wav")
            if not os.path.exists(dest):
                with open(dest, "wb") as handle:
                    handle.write(zf.read(member))
            out[name] = dest
    return out


def ffmpeg_read(path, channels, start_s, duration_s):
    """Decode path to float32 PCM at SAMPLE_RATE_HZ with the requested channel count."""
    cmd = ["ffmpeg", "-v", "error"]
    if start_s:
        cmd += ["-ss", str(start_s)]
    cmd += ["-i", path]
    if duration_s:
        cmd += ["-t", str(duration_s)]
    cmd += ["-f", "f32le", "-ac", str(channels), "-ar", str(SAMPLE_RATE_HZ), "-"]
    proc = subprocess.run(cmd, capture_output=True, check=True)
    return np.frombuffer(proc.stdout, dtype=np.float32).astype(np.float64)


def load_iq(path, start_s, duration_s):
    raw = ffmpeg_read(path, 2, start_s, duration_s)
    return raw[0::2] + 1j * raw[1::2]


def remodulate(audio, deviation):
    """Integrate discriminator audio back into complex baseband (inverse FM demod)."""
    audio = audio - np.mean(audio)
    scale = np.percentile(np.abs(audio), 99.5)
    if scale <= 0.0:
        scale = 1.0
    freq = audio / scale * deviation
    phase = np.cumsum(freq) * math.pi
    return np.exp(1j * phase)


def to_cu8(samples, headroom=0.9):
    """Quantize complex baseband to interleaved unsigned 8-bit I/Q."""
    real = np.real(samples)
    imag = np.imag(samples)
    peak = max(np.max(np.abs(real)), np.max(np.abs(imag)))
    if peak <= 0.0:
        peak = 1.0
    interleaved = np.empty(len(samples) * 2)
    interleaved[0::2] = real / peak * headroom
    interleaved[1::2] = imag / peak * headroom
    return np.clip(np.round(interleaved * 127.5 + 127.5), 0, 255).astype(np.uint8)


def write_fixture(out_dir, name, samples):
    payload = to_cu8(samples)
    data_name = name + ".iq"
    data_path = os.path.join(out_dir, data_name)
    with open(data_path, "wb") as handle:
        handle.write(payload.tobytes())
    metadata = METADATA_TEMPLATE.format(
        sample_rate=SAMPLE_RATE_HZ,
        bw_khz=DSP_BW_KHZ,
        demod_rate=SAMPLE_RATE_HZ,
        data_file=data_name,
        data_bytes=len(payload),
    )
    with open(data_path + ".json", "w", encoding="utf-8") as handle:
        handle.write(metadata)
    return len(payload)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", default=os.path.join("tests", "fixtures", "iq"))
    parser.add_argument("--cache", default=".iq-fixture-cache")
    args = parser.parse_args()

    os.makedirs(args.out, exist_ok=True)
    os.makedirs(args.cache, exist_ok=True)

    resolved = {}
    for key, url in SOURCES.items():
        path = fetch(args.cache, key, url)
        if key in ZIP_MEMBERS:
            resolved.update(extract_zip_members(args.cache, key, path))
        else:
            resolved[key] = path

    total = 0
    for name, source_key, kind, start_s, duration_s, deviation in FIXTURES:
        path = resolved[source_key]
        if kind == "iq":
            samples = load_iq(path, start_s, duration_s)
        else:
            audio = ffmpeg_read(path, 1, start_s, duration_s)
            samples = remodulate(audio, deviation or DEFAULT_DEVIATION)
        written = write_fixture(args.out, name, samples)
        total += written
        print(f"{name:16s} {kind:5s} {written // 1024:6d} KiB")
    print(f"total {total // 1024} KiB in {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
