name: windows-cygwin-portable

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

jobs:
  build-portable-zip:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Gate on CI success (ci.yml) [disabled]
        if: ${{ false }}
        uses: actions/github-script@v8
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const sha = context.sha;
            // Check latest run of the Linux CI workflow for this commit
            const res = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'ci.yml',
              head_sha: sha,
              per_page: 1
            });
            const run = res.data.workflow_runs[0];
            if (!run) {
              core.setFailed(`No CI (ci.yml) run found for commit ${sha}.`);
            } else if (run.status !== 'completed' || run.conclusion !== 'success') {
              core.setFailed(`CI (ci.yml) not successful for ${sha}. status=${run.status} conclusion=${run.conclusion}`);
            } else {
              core.info(`CI passed: ${run.html_url}`);
            }

      - name: Compute dependency SHAs
        id: dep-shas
        shell: pwsh
        run: |
          $mbe = (git ls-remote https://github.com/arancormonk/mbelib-neo HEAD).Split("`t")[0]
          "mbe_sha=$mbe" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Setup Cygwin
        uses: egor-tensin/setup-cygwin@v4.0.1
        with:
          platform: x64
          packages: >-
            git
            gcc-g++
            make
            cmake
            curl
            ninja
            pkg-config
            libsndfile-devel
            itpp-devel
            ncursesw-devel
            libpulse-devel
            pulseaudio
            pulseaudio-utils
            librtlsdr-devel
            libusb1.0-devel
            mintty

      - name: Mark repo safe for Cygwin git
        shell: pwsh
        run: C:\\tools\\cygwin\\bin\\bash.exe -lc 'git config --global --add safe.directory "$(cygpath -u "$GITHUB_WORKSPACE")"'

      - name: Restore cygdeps cache
        uses: actions/cache@v4.2.4
        with:
          path: .cygdeps
          key: cygdeps-${{ runner.os }}-${{ steps.dep-shas.outputs.mbe_sha }}
          restore-keys: |
            cygdeps-${{ runner.os }}-

      - name: Show Cygwin versions
        shell: pwsh
        run: C:\\tools\\cygwin\\bin\\bash.exe -lc 'uname -a; cmake --version; gcc --version'

      - name: Prepare deps environment
        shell: pwsh
        run: |
          C:\\tools\\cygwin\\bin\\bash.exe -lc 'WS="$(cygpath -u "$GITHUB_WORKSPACE")"; cd "$WS"; DEPS_PREFIX="$WS/.cygdeps"; echo "DEPS_PREFIX=$DEPS_PREFIX" >> "$GITHUB_ENV"; echo "CMAKE_PREFIX_PATH=$DEPS_PREFIX:${CMAKE_PREFIX_PATH:-}" >> "$GITHUB_ENV"; echo "PKG_CONFIG_PATH=$DEPS_PREFIX/lib/pkgconfig:$DEPS_PREFIX/lib64/pkgconfig:${PKG_CONFIG_PATH:-}" >> "$GITHUB_ENV"; echo "PATH=$DEPS_PREFIX/bin:${PATH}" >> "$GITHUB_ENV"; echo "LD_LIBRARY_PATH=$DEPS_PREFIX/bin:$DEPS_PREFIX/lib:$DEPS_PREFIX/lib64:${LD_LIBRARY_PATH:-}" >> "$GITHUB_ENV"'

      - name: Download mbelib-neo source (tarball)
        shell: pwsh
        run: |
          C:\\tools\\cygwin\\bin\\bash.exe -lc 'cd "$(cygpath -u "$GITHUB_WORKSPACE")"; curl -L -o mbelib-neo.tar.gz https://github.com/arancormonk/mbelib-neo/archive/refs/heads/main.tar.gz && ls -l mbelib-neo.tar.gz'

      - name: Build mbe-neo (static or shared)
        shell: pwsh
        run: |
          C:\\tools\\cygwin\\bin\\bash.exe -lc 'set -euo pipefail; WS="$(cygpath -u "$GITHUB_WORKSPACE")"; cd "$WS"; if [ ! -f "$DEPS_PREFIX/lib/pkgconfig/libmbe-neo.pc" ] && [ ! -f "$DEPS_PREFIX/lib64/pkgconfig/libmbe-neo.pc" ]; then echo "Extracting mbelib-neo.tar.gz in $WS"; tar -xzf mbelib-neo.tar.gz || true; D="mbelib-neo-main"; if [ ! -d "$D/src/ambe" ]; then echo "Tarball extract missing expected tree; falling back to git clone"; rm -rf "$D" mbelib-neo || true; git clone --depth 1 https://github.com/arancormonk/mbelib-neo.git mbelib-neo; D="mbelib-neo"; fi; echo "Using source dir: $D"; test -d "$D/src/ambe" && ls -la "$D/src/ambe" || true; cmake -S "$D" -B "$D/build" -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$DEPS_PREFIX" -DMBELIB_BUILD_TESTS=OFF -DMBELIB_BUILD_EXAMPLES=OFF; cmake --build "$D/build" -j; cmake --install "$D/build"; else echo "Using cached mbelib-neo in $DEPS_PREFIX"; fi'

      - name: Configure (Release)
        shell: pwsh
        run: |
          C:\\tools\\cygwin\\bin\\bash.exe -lc 'cd "$(cygpath -u "$GITHUB_WORKSPACE")" && cmake --preset dev-release -DDSD_ENABLE_LTO=OFF'

      - name: Build
        shell: pwsh
        run: |
          C:\\tools\\cygwin\\bin\\bash.exe -lc 'cd "$(cygpath -u "$GITHUB_WORKSPACE")" && cmake --build --preset dev-release -j'

      - name: Stage portable tree
        id: stage
        shell: pwsh
        run: |
          C:\\tools\\cygwin\\bin\\bash.exe -lc 'cd "$(cygpath -u "$GITHUB_WORKSPACE")"; EXE="build/dev-release/apps/dsd-cli/dsd-neo.exe"; test -f "$EXE"; STAGE="dist/dsd-neo-cygwin"; mkdir -p "$STAGE/bin" "$STAGE/etc"; cp -f "$EXE" "$STAGE/bin/"; cygcheck -v "$EXE" | sed -n "s/^ *\([A-Za-z]:\\\\[^ ]*\.dll\).*/\1/p" | sort -u > dlls.txt || true; while IFS= read -r f; do if [ -f "$f" ]; then cp -n "$f" "$STAGE/bin/" || true; fi; done < dlls.txt; PULSEAUDIO_BIN="$(command -v pulseaudio || true)"; if [ -n "$PULSEAUDIO_BIN" ]; then cp -f "$PULSEAUDIO_BIN" "$STAGE/bin/"; cygcheck -v "$PULSEAUDIO_BIN" | sed -n "s/^ *\([A-Za-z]:\\\\[^ ]*\.dll\).*/\1/p" | sort -u > padlls.txt || true; while IFS= read -r f; do if [ -f "$f" ]; then cp -n "$f" "$STAGE/bin/" || true; fi; done < padlls.txt; fi; MINTTY_BIN="$(command -v mintty || true)"; if [ -n "$MINTTY_BIN" ]; then cp -f "$MINTTY_BIN" "$STAGE/bin/"; cygcheck -v "$MINTTY_BIN" | sed -n "s/^ *\([A-Za-z]:\\\\[^ ]*\.dll\).*/\1/p" | sort -u > mtdlls.txt || true; while IFS= read -r f; do if [ -f "$f" ]; then cp -n "$f" "$STAGE/bin/" || true; fi; done < mtdlls.txt; fi; cp -f packaging/windows-cygwin/run-dsd-neo.bat "$STAGE/"; cp -f packaging/windows-cygwin/run-dsd-neo-mintty.bat "$STAGE/" 2>/dev/null || true; cp -f packaging/windows-cygwin/README-windows.txt "$STAGE/"; if [ -f packaging/windows-cygwin/etc/pulse/default.pa ]; then mkdir -p "$STAGE/etc/pulse"; cp -f packaging/windows-cygwin/etc/pulse/default.pa "$STAGE/etc/pulse/"; fi'

      - name: Archive ZIP
        shell: pwsh
        env:
          REF_TYPE: ${{ github.ref_type }}
          REF_NAME: ${{ github.ref_name }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          $stage = 'dist/dsd-neo-cygwin'
          $defaultZip = "$stage.zip"
          if ($env:REF_TYPE -eq 'tag' -and $env:REF_NAME) {
            $zip = "dist/dsd-neo-cygwin-$($env:REF_NAME).zip"
            $artName = "dsd-neo-cygwin-portable-$($env:REF_NAME)"
          } else {
            $short = if ($env:GITHUB_SHA) { $env:GITHUB_SHA.Substring(0,7) } else { "dev" }
            $zip = "dist/dsd-neo-cygwin-$short.zip"
            $artName = "dsd-neo-cygwin-portable-$short"
          }
          $zipDir = Split-Path -Parent $zip
          if ($zipDir -and !(Test-Path $zipDir)) { New-Item -Type Directory -Force -Path $zipDir | Out-Null }
          if (Test-Path $zip) { Remove-Item -Force $zip }
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::CreateFromDirectory($stage, $zip)
          Write-Host "Created: $zip"
          echo "ZIP_PATH=$zip" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "ART_NAME=$artName" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        id: zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ steps.zip.outputs.ART_NAME }}
          path: ${{ steps.zip.outputs.ZIP_PATH }}

      - name: Upload release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.zip.outputs.ZIP_PATH }}
          name: dsd-neo portable (Cygwin) ${{ github.ref_name }}
          generate_release_notes: true
